music_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_world.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('userpost.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings. MEDIA_ROOT)

music_world/urls.py
from django.urls import path
from .views import *


app_name = "events"

urlpatterns = [
    path("", views_index, name="musics_index"),
    path("events/", views_event, name="musics_event"),
    path("show/<uuid:pk>", views_show, name="musics_show"),
]

reviews/urls.py
from django.urls import path
from .views import *

app_name = 'reviews'

urlpatterns = [
    # path("", views_index, name="reviews_index"),
    path("event/<uuid:event>", views_create, name="review_create"),
]

userpost/urls.py
from django.urls import path
from .views import *


app_name = "posts"

urlpatterns = [
    path("", views_post_index, name="post-index"),
    path("create", views_post, name="post-create"),
    path("show/<uuid:pk>", views_postShow, name="posts_show"),
    path("category/", views_create_category, name="category_create"),
    path("comment/<uuid:post>", views_comment, name="comment_create"),
]

music_world/models.py
from django.db import models
import uuid

# Create your models here.



class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    title = models.CharField(max_length=100, null=False)
    events_date_time = models.DateTimeField(auto_now=False, auto_now_add=False)
    location = models.CharField(max_length=200, null=False)
    description = models.TextField()

    cover = models.ImageField(upload_to='uploads/%Y/%m/%d')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title



music_world/forms.py
from django import forms 
from .models import *
from django.forms import widgets



class EventForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = '__all__'

        widgets = {
            'title' : forms.TextInput(attrs={
                'class': 'form-control', 
                'placeholder': 'Events Title'
            }),
            'events_date_time' : forms.DateTimeInput(attrs={
                'class': 'form-control datetimepicker-input',
                'data-target': '#datetimepicker1',
                'placeholder': 'yyyy-mm-dd  00:00'
            }),
            'location' : forms.TextInput(attrs={
                'class': 'form-control', 
                'placeholder': 'Events Location'
            }),
            'description' : forms.Textarea(attrs={
                'class': 'form-control', 
                'placeholder': 'Events Description'
            }),
            'cover': forms.FileInput(attrs={
                'class': 'form-control'
            })
        }



music_world/views.py
from reviews.forms import ReviewForm
from music_world.forms import EventForm
from music_world.models import Event
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from userpost.views import Post
import uuid

# Create your views here.
@login_required
def views_index(request):

    events = Event.objects.all()
    posts = Post.objects.all()
    return render(request, 'musics/index.html',{"events":events, "posts":posts})


@login_required
def views_event(request):
    form = EventForm()
    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = Event(
                title=request.POST['title'],
                events_date_time=request.POST['events_date_time'],
                location=request.POST['location'],
                description=request.POST['description'],
                cover=request.FILES['cover']
                )
            
            event.save()
            return redirect('events:musics_index')
    
    events = Event.objects.all()

    context = {"form":form, "events":events}
    return render(request, 'musics/events.html', context)

@login_required
def views_show(request, pk):
    try:
        event = Event.objects.get(pk=pk)
    except Event.DoesNotExist:
        return redirect('events:musics_index')

    if request.GET.get('action') == 'del':
        event.delete()
        return redirect('events:musics_index')

    if request.method == 'POST' and request.GET['action'] == 'edit':
        form = EventForm(request.POST, request.FILES, instance=event)

        if form.is_valid():
            form.save()
            return redirect('events:musics_show', event.id)
        
    if request.GET.get('action') == 'edit':
        form = EventForm(instance=event)

        context = {"form":form, "event":event, "edit":True}
        return render(request, 'musics/show.html', context)


    review_form = ReviewForm()

    context = {"event":event, "edit":False, "review_form":review_form}
    return render(request, 'musics/show.html', context)


music_world/templates/musics/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'events:musics_index'%}">Music World</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'events:musics_event'%}">Events</a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Profile</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock body %}

    {% block scripts %}{% endblock scripts %}
</body>
</html>

music_world/templates/musics/events.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="container">
    <h1 class="text-center">Events Page</h1>
    <div class="row">
        <div class="col-md-4">
            <form class="user-post" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button class="btn btn-primary" type="submit">Add Events</button>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

music_world/templates/musics/index.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div class="container">
    <div class="event-post">
        <h1>Music Events</h1>
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                {% for event in events %}
                <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                    <div class="card-footer">
                        <small class="text-muted">Posted by organiser - </small>
                        <small class="text-muted">Date posted: {{ event.created_at|date:"F d, Y" }}</small>
                    </div>
                    <a href="{% url 'events:musics_show' event.id%}"><img src="{{event.cover.url}}" class="card-img-top" /></a>
                    <div class="card-body">
                        <h5 class="card-title">{{event.title}}</h5>
                        <p class="card-text">Event Date: {{event.events_date_time}}</p>
                    </div>
                </div>
                {% empty %}

                <div class="alert alert-warning">
                    No Events added yet
                </div>

                {% endfor %}
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                {% for post in posts %}
                <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                    <div class="card-header d-flex justify-content-between">
                        <div class="profile-pic">
                            <img class="rounded-circle article-img" width="60" height="60" src="{{ post.username.profile.image.url }}">
                        </div>
                        <small class="text-muted">Posted by: </small>
                        <div class="username">
                            <p class="card-text"><h5>{{post.username}}</h5></p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Date posted: {{ post.created_at|date:"F d, Y" }}</small>
                    </div>
                    <a href="{% url 'posts:posts_show' post.id%}"><img src="{{post.cover.url}}" class="card-img-top" /></a>
                    <div class="card-body">
                        <h5 class="card-title">{{post.title}}</h5>
                        <p class="card-text">Event Date: {{post.events_date_time}}</p>
                    </div>
                </div>
                {% empty %}

                <div class="alert alert-warning">
                    No User Posted Yet
                </div>

                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock body %}

music_world/templates/musics/show.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow-lg p-3">
                    <img src="{{event.cover.url}}" class="card-img-top" />
                    <h3>{{event.title}}</h3>
                    <h4>Schedule: {{event.events_date_time}}</h4>
                    <h4>Avenue: {{event.location}}</h4>
                    
                    <h5>Description:</h5>
                    <p>{{event.description}}</p>
                    {% if request.user.is_superuser %}
                    <div class="d-grid gap-2 ">
                        <a class="btn btn-primary" role="button" href="{% url "events:musics_show" event.id %}?action=edit">Edit</a>
                        <a class="btn btn-primary" role="button" href="{% url "events:musics_show" event.id %}?action=del">Delete</a>
                    </div>
                    {% endif %}
                </div> 
            </div>
            {% if edit %} 
            <div class="col-md-6">
                <form action="{% url 'events:musics_show' event.id %}?action=edit" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form}}
                    <div class="d-grid gap-2 d-md-block">
                        <button class="btn btn-primary" type="submit">Edit Events</button>
                        <a class="btn btn-primary" role="button" href="{% url "events:musics_show" event.id %}">Cancel</a>
                    </div> 
                </form>
            </div>
            {% endif %}
            <div class="col">
                <div class="card shadow-lg p-3">
                    <h4 class="text-center fw-bold">Reviews</h4>
                        <div class="comments">
                            {% for r in event.reviews.all %}
                            <div class="card text-center shadow-lg p-3">
                                <div class="card-header">
                                    <h5 class="card-title">{{r.user.username}}</h5>
                                </div>
                                <div class="card-body">    
                                    <p class="card-text">{{r.review}}</p>       
                                </div>
                                <div class="card-footer text-muted">
                                    <small class="text-muted">Date posted: {{ event.created_at|date:"F d, Y" }}</small>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% if request.user.profile %}
                <div class="form-floating">
                    <h2>Comments</h2>
                    <form action="{% url 'reviews:review_create' event.id %}" method="post">
                        {% csrf_token %}
                        {{review_form}}
                        <button class="btn btn-primary" type="submit">Send</button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>



{% endblock body %}