accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = "accounts"

urlpatterns = [
    path('register/', views_register, name="register"),
    path('login/', views_login, name="login"),
    path('logout/', views_logout, name="logout"),
    path('profile/', views_profile, name="profile")
]

music_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_world.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('userpost.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings. MEDIA_ROOT)

music_world/urls.py
from django.urls import path
from .views import *


app_name = "events"

urlpatterns = [
    path("", views_index, name="musics_index"),
    path("events/", views_event, name="musics_event"),
    path("show/<uuid:pk>", views_show, name="musics_show"),
]

reviews/urls.py
from django.urls import path
from .views import *

app_name = 'reviews'

urlpatterns = [
    # path("", views_index, name="reviews_index"),
    path("event/<uuid:event>", views_create, name="review_create"),
]

userpost/urls.py
from django.urls import path
from .views import *


app_name = "posts"

urlpatterns = [
    path("", views_post_index, name="post-index"),
    path("create", views_post, name="post-create"),
    path("show/<uuid:pk>", views_postShow, name="posts_show"),
    path("category/", views_create_category, name="category_create"),
    path("comment/<uuid:post>", views_comment, name="comment_create"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'musics/main.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
    <title>Document</title>

</head>
<body>
    
    <header class="site-header">
        <nav class="navbar navbar-expand-lg p-3 shadow-lg navbar-dark bg-dark md-3">
            <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'events:musics_index'%}">
            <img src="{% static 'image/music_logo.jpg' %}" style="width:50px;height:50px;" class="logo d-inline-block align-text-top">
            Music World
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    {% if request.user.is_superuser %}
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'posts:category_create' %}">Category</a>
                        <a class="nav-item nav-link" href="{% url 'events:musics_event'%}">Events</a>
                        <a class="nav-item nav-link" href="{% url 'posts:post-index' %}">User Posted</a>
                    </div>
                    {% endif %}
                    <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        {% if request.user.profile %}
                        <a class="nav-item nav-link" href="{% url 'posts:post-create'%}">New Post</a>
                        <a class="nav-item nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                        {% endif %}
                        <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
<div class="container">

    {% if messages %}
        {% for message in messages %}

            <div class="alert alert-warning">
                {{message}}
            </div>
    
        {% endfor %}
        {% endif %}
        
        
    
    
    {% block body %}
    {% endblock body %}
    {% block content %}
    {% endblock content %}

    {% block scripts %}{% endblock scripts %}

</div>
</body>
</html>