music_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_world.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('userpost.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings. MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from .views import *

app_name = 'reviews'

urlpatterns = [
    # path("", views_index, name="reviews_index"),
    path("event/<uuid:event>", views_create, name="review_create"),
]

userpost/urls.py
from django.urls import path
from .views import *


app_name = "posts"

urlpatterns = [
    path("", views_post_index, name="post-index"),
    path("create", views_post, name="post-create"),
    path("show/<uuid:pk>", views_postShow, name="posts_show"),
    path("category/", views_create_category, name="category_create"),
    path("comment/<uuid:post>", views_comment, name="comment_create"),
]

userpost/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
import uuid

# Create your models here.
class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    name = models.CharField(max_length=200, null=False)
    
    def __str__(self):
        return self.name


    

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    username = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    events_date_time = models.DateTimeField(auto_now=False, auto_now_add=False)
    location = models.CharField(max_length=200, null=False)
    description = models.TextField()
    

    cover = models.ImageField(upload_to='uploads/%Y/%m/%d')
    categories = models.ManyToManyField(Category, related_name='posts')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('post-create', kwargs={'pk': self.pk})


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    

    comment = models.TextField(null=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

    

userpost/forms.py
from django import forms 
from .models import *
from .views import *
from django.forms import widgets
from bootstrap_datepicker_plus import DatePickerInput

class PostForm(forms.ModelForm):

    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple()
    )
    
    class Meta:
        model = Post
        fields = ("title","events_date_time","location","description","cover",)

        widgets = {
            'title' : forms.TextInput(attrs={
                'class': 'form-control', 
                'placeholder': 'Events Title'
            }),
            'events_date_time' : forms.DateTimeInput(attrs={
                'class': 'form-control',
                'data-target': 'datetimepicker',
                'placeholder': 'yyyy-mm-dd  00:00'
            }),
            'location' : forms.TextInput(attrs={
                'class': 'form-control', 
                'placeholder': 'Events Location'
            }),
            'description' : forms.Textarea(attrs={
                'class': 'form-control', 
                'placeholder': 'Events Description'
            }),
            'cover': forms.FileInput(attrs={
                'class': 'form-control'
            })
        }

class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category
        fields = '__all__'

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        exclude = ('user','post',)

        widgets = {
            'comment' : forms.Textarea(attrs={
                'class': 'form-control', 
                'placeholder': 'Review'
            }),
            
        }


userpost/views.py
from .forms import CategoryForm, PostForm, CommentForm
from .models import Post
from music_world.views import Event
from accounts.models import User
from django.shortcuts import redirect, render
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required



# Create your views here.

@login_required
def views_post_index(request):

    posts = Post.objects.all()
    return render(request, 'posts/index.html',{"posts":posts})


@login_required
def views_post(request):
    form = PostForm()

    if request.method == "POST":
        user = User.objects.get(pk=request.user.id)
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = Post(
                username=user,
                title=request.POST['title'],
                events_date_time=request.POST['events_date_time'],
                location=request.POST['location'],
                description=request.POST['description'],
                cover=request.FILES['cover']
                )
            
            post.save()
            categories = form.cleaned_data['categories']
            for cat in categories:
                post.categories.add(cat)
            return redirect('events:musics_index')
    
    posts = Post.objects.all()

    context = {"form":form, "posts":posts}
    return render(request, 'posts/post.html', context)


@login_required
def views_postShow(request, pk):
    
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        return redirect('posts:post-index')

    if request.GET.get('action') == 'del':
        post.delete()
        return redirect('posts:post-index')

    if request.method == 'POST' and request.GET['action'] == 'edit':
        form = PostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save()
            return redirect('posts:posts_show', post.id)
        
    if request.GET.get('action') == 'edit':
        form = PostForm(instance=post)

        context = {"form":form, "post":post, "edit":True}
        return render(request, 'posts/show.html', context)
    
    comment_form = CommentForm()

    context = {"post":post, "edit":False, "comment_form":comment_form}
    return render(request, 'posts/show.html', context)

@login_required
def views_create_category(request):

    category_form = CategoryForm()
    if request.method == 'POST':
        category_form = CategoryForm(request.POST)
        if category_form.is_valid():
            category_form.save()
            return redirect('posts:category_create')

    context = {"category_form":category_form}
    return render(request, 'posts/create_category.html', context)

    
@login_required
def views_comment(request, post):
    if request.method == 'POST':

        form = CommentForm(request.POST)
        if form.is_valid():
            
            
            post = Post.objects.get(pk=post)
            post.comments.create(user=request.user, comment=request.POST['comment'])

            return redirect('posts:posts_show', post.id)
    return HttpResponse({"message": "works"})

    

userpost/templates/posts/create_category.html
{% extends 'base.html' %}

{% block body %}
<main class="container">
 <h1>Instruments Category</h1>
{% if request.user.is_superuser %}
<div class="category">
    <form action="" method="POST">
        {% csrf_token %}
        {{category_form}}

        <button class="btn btn-primary" type="submit">Add Category</button>

    </form>
</div>
{% endif %}
</main>
{% endblock body %}

userpost/templates/posts/index.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            {% for post in posts %}
            <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                <div class="card-header d-flex justify-content-between">
                    <div class="profile-pic">
                        <img class="rounded-circle article-img" width="60" height="60" src="{{ post.username.profile.image.url }}">
                    </div>
                    <div class="username">
                        <p class="card-text"><h5>{{post.username}}</h5></p>
                    </div>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Date posted: {{ post.created_at|date:"F d, Y" }}</small>
                </div>
                <a href="{% url 'posts:posts_show' post.id%}"><img src="{{post.cover.url}}" class="card-img-top" /></a>
                <div class="card-body">
                    <h5 class="card-title">{{post.title}}</h5>
                    <p class="card-text">Date: {{post.events_date_time}}</p>
                </div>
            </div>
            {% empty %}

            <div class="alert alert-warning">
                No User Posted Yet
            </div>

            {% endfor %}
        </div>
    </div>
</div>

{% endblock body %}



userpost/templates/posts/post.html
{% extends "base.html" %}

{% block body %}
    <div class="container">
        <h1 class="text-center">User Post</h1>
        <div class="row">
            <div class="col-md-4">
                <form class="user-post" action="{% url 'posts:post-create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    {{form}}
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button class="btn btn-primary" type="submit">Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

userpost/templates/posts/show.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow-lg p-3">
                    <img src="{{post.cover.url}}" class="card-img-top" />
                    <h3>{{post.title}}</h3>
                    <h4>Schedule: {{post.events_date_time}}</h4>
                    <h4>Avenue: {{post.location}}</h4>
                    <h4>Instruments:</h4>
                    {% for cat in post.categories.all %}
                    <li>{{cat.name}}</li>
                    {% endfor %}
                    <h5>Description:</h5>
                    <p>{{post.description}}</p>
                    
                    {% comment %} {% if post.user.profile %}  {% endcomment %}
                    <div class="d-grid gap-2 ">
                        {% if request.user.profile %}
                        <a class="btn btn-primary" role="button" href="{% url "posts:posts_show" post.id %}?action=edit">Edit</a>
                        {% endif %}
                        <a class="btn btn-primary" role="button" href="{% url "posts:posts_show" post.id %}?action=del">Delete</a>
                    </div> 
                    {% comment %} {% endif %}  {% endcomment %}
                </div> 
            </div>
            {% if edit %} 
            <div class="col-md-6">
                <form action="{% url 'posts:posts_show' post.id %}?action=edit" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form}}
                    <div class="d-grid gap-2 d-md-block">
                        <button class="btn btn-primary" type="submit">Send</button>
                        <a class="btn btn-primary" role="button" href="{% url "posts:posts_show" post.id %}">Cancel</a>
                    </div> 
                </form>
            </div>
            {% endif %}
            <div class="col">
                <div class="card shadow-lg p-3">
                    <h4 class="text-center fw-bold">Reviews</h4>
                        <div class="comments">
                            {% for p in post.comments.all %}
                            <div class="card text-center shadow-lg p-3">
                                <div class="card-header">
                                    <h5 class="card-title">{{p.user.username}}</h5>
                                </div>
                                <div class="card-body">    
                                    <p class="card-text">{{p.comment}}</p>       
                                </div>
                                <div class="card-footer text-muted">
                                    <small class="text-muted">Date posted: {{ post.created_at|date:"F d, Y" }}</small>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% if request.user.profile %}
                <div class="form-floating">
                    <h2>Comments</h2>
                    <form action="{% url 'posts:comment_create' post.id %}" method="post">
                        {% csrf_token %}
                        {{comment_form}}
                        <button class="btn btn-primary" type="submit">Send</button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>



{% endblock body %}